---
- name: Converge
  hosts: all
    roles:
    - role: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
  tasks:
    - name: "Include addusers_test"
      include_role:
        name: "addusers_test"
